### ISSUE TITLE
Linker error

### ISSUE THREAD

**Issue by jhuh3226** [johanGelinder/KinectTutorial#1]
Hi, have followed the same tutorial [https://www.youtube.com/watch?v=bA3JwQ2KV2M] but there is a problem with linker after copying (dragging) libOpenNI.dylib file.

error:

```
ld: library not found for -lOpenNI
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

How should I solve this error?

**Comment by johanGelinder** [comment]
Hi,

Linker errors is unfortunately always an issue working with c++.
Could you perhaps share more of your error log?

Have you cloned the code from my github repo by any chance? Some people
have been having issues due to the linker pointing at the wrong data path.

Check you error log if you might find this line:
* L/Users/johangelinder/Desktop/openFrameworks/addons/ofxOpenNINew/lib'.*
If you do, let me know and I can guide you through on how to change it.


All the best,

Johan
